name: 'dbt_getground'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_getground'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  dbt_getground:
    # Config indicated by + and applies to all files under models/example/
    example:
      +materialized: view

seeds:
  dbt_getground:
    partners:
      +column_types:
        created_at: float
        updated_at: float

    referrals:
      +column_types:
        created_at: float
        updated_at: float

vars:
  # date we'll use at current_date given data is not up dated.
  case_current_date: "'2021-05-05'"