
version: 2

models:
  - name: staging__partners
    description: This table pull partners details from the source and recast the columns types
    columns:
      - name: id
        description: The primary key for this table
        tests:
          - unique
          - not_null
      - name: created_at
        description: Time the partner was created
        tests:
          - not_null
      - name: updated_at
        description: Time the partner was updated
        tests:
          - not_null
      - name: partner_type
        description: Partner type
        tests:
          - not_null
      - name: lead_sales_contact
        description: Our sales person responsible for the account
        tests:
          - not_null

  - name: staging__referrals
    description: This table pull referrrals details from the source and recast the columns types
    columns:
      - name: id
        description: The primary key for this table
        tests:
          - unique
          - not_null
      - name: created_at
        description: time referral was created
        tests: 
          - not_null
      - name: updated_at
        description: time when the referral status went from `pending` to either `disinterested` or `successful`
        tests:
          - not_null 
      - name: company_id
        description: company id from the referred company
        tests:
          - not_null
      - name: partner_id
        description: partner id from the referral partner
        tests:
          - not_null
      - name: consultant_id
        description: id from the referral consultant in the partner
        tests:
          - not_null
      - name: status 
        description: current status of the referral
        tests:
          - not_null
          - accepted_values:
              values: ['pending', 'disinterested', 'successful']
      - name: is_outbound
        description: whether referral is outbound or inbound
        tests:
          - not_null

  - name: staging__sales_people
    description: This table pull sales people details from the source and recast the columns types
    columns:
      - name: name
        description: The name of the sales person
        tests:
          - unique
          - not_null
      - name: country
        description: The country where the sales person is based
        tests:
          - not_null
